spring.application.name=results-service
server.port=${PORT:8083}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT:6379}

springdoc.api-docs.path=/api/v1/docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.org.springframework=INFO
logging.level.com.electoral=DEBUG